---
# Host vars for the molecule test host "lamp" (phpfpm).

# Role-specific vars.
lamp_configure:
  - apt
  - files
  - mysql
  - apache
  - php
  - fpm

# App vars.
app_hostname: "lamp"
app_vhost_dir: "/var/www/{{ app_hostname }}"
app_vhost_docroot: "{{ app_vhost_dir }}/web"

# geerlingguy.apache vars.
apache_vhosts:
  - servername: "{{ app_hostname }}"
    documentroot: "{{ app_vhost_docroot }}"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ app_vhost_docroot }}"

# geerlingguy.mysql vars.
mysql_root_password: "lamp_root_password"
mysql_databases:
  - name: "lamp_db"
    encoding: "utf8"
    collation: "utf8_general_ci"
mysql_users:
  - name: "lamp_user"
    host: "localhost"
    password: "lamp_user_password"
    priv: "lamp_db.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"

# geerlingguy.php vars.
php_enable_fpm: true

# weareinteractive.apt vars.
apt_repositories:
  - repo: "ppa:ondrej/php"
    codename: xenial
    update_cache: true
