---
- name: Converge
  hosts: all

  vars:
    # geerlingguy.php vars.
    #
    # This variable included here to demonstrate that in-playbook vars are
    # correctly inherited.
    php_default_version_debian: "7.0"

  roles:
    - role: ansible-role-lamp

  post_tasks:
    - name: Create a test PHP file.
      copy:
        src: "{{ playbook_dir }}/../files/index.php"
        dest: "/var/www/lamp/web/index.php"
        owner: "jenkins"
        group: "jenkins"
        mode: "u=rw,go=r"
