---
- name: Converge
  hosts: all

  vars:
    # geerlingguy.php vars.
    #
    # This variable included here to demonstrate that in-playbook vars are
    # correctly inherited.
    php_default_version_debian: "7.3"

  roles:
    - role: ansible-role-lamp
