---
- name: Prepare
  hosts: all

  vars:
    # weareinteractive.apt vars.
    apt_packages:
      - curl

  pre_tasks:
    - name: Create jenkins user.
      user:
        name: "jenkins"

  roles:
    - role: weareinteractive.apt
