---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: lamp
    image: geerlingguy/docker-ubuntu1604-ansible
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: phpfpm
verifier:
  name: testinfra
  lint:
    name: flake8
