---
- name: Converge
  hosts: all

  vars:
    # ctorgalson.lamp vars.
    lamp_configure:
      - files
      - ssl
      - mysql
      - apache
      - php
      - fpm
      - composer

    # geerlingguy.apache vars.
    apache_vhosts:
      - servername: "{{ app_hostname }}"
        documentroot: "{{ app_vhost_docroot }}"
        extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ app_vhost_docroot }}"
    apache_vhosts_ssl:
      - servername: "{{ app_hostname }}"
        documentroot: "{{ app_vhost_docroot }}"
        certificate_file: "{{ app_ssl_cert_dir }}/{{ app_ssl_cert_filename }}"
        certificate_key_file: "{{ app_ssl_private_dir }}/{{ app_ssl_key_filename }}"
        extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ app_vhost_docroot }}"
    apache_mods_enabled:
      - "expires.load"
      - "headers.load"
      - "proxy.load"
      - "rewrite.load"
      - "ssl.load"

    # geerlingguy.php vars.
    php_packages:
      - "libpcre3-dev"
      - "php{{ php_default_version_debian }}-cli"
      - "php{{ php_default_version_debian }}-common"
      - "php{{ php_default_version_debian }}-curl"
      - "php{{ php_default_version_debian }}-dev"
      - "php{{ php_default_version_debian }}-fpm"
      - "php{{ php_default_version_debian }}-gd"
      - "php{{ php_default_version_debian }}-imap"
      - "php{{ php_default_version_debian }}-json"
      - "php{{ php_default_version_debian }}-mbstring"
      - "php{{ php_default_version_debian }}-mysql"
      - "php{{ php_default_version_debian }}-opcache"
      - "php{{ php_default_version_debian }}-pdo"
      - "php{{ php_default_version_debian }}-xml"
      - "php{{ php_default_version_debian }}-zip"
      - "php-sqlite3"
      - "php-apcu"
      - "php-redis"
    php_enable_php_fpm: true

  roles:
    - role: ansible-role-lamp

  post_tasks:
    - name: Run common post_tasks.
      include_tasks: "{{ playbook_dir }}/../tasks/post.yml"
