---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-lamp

  post_tasks:
    - name: Create a test PHP file.
      copy:
        src: "{{ playbook_dir }}/../files/index.php"
        dest: "/var/www/lamp/web/index.php"
        owner: "jenkins"
        group: "jenkins"
        mode: "u=rw,go=r"
      changed_when: false
