---
- name: Prepare
  hosts: all

  vars:
    # ctorgalson.files vars.
    files_files:
      - path: "/var/www/lamp/web"
        state: directory
        owner: "jenkins"
        group: "www-data"
        mode: "ug=rwx,o=rx"

    # weareinteractive.apt vars.
    apt_packages:
      - curl

  pre_tasks:
    - name: Create jenkins user.
      user:
        name: "jenkins"

  roles:
    - role: weareinteractive.apt
    - role: ctorgalson.files

  post_tasks:
    - name: Create a test PHP file.
      copy:
        content: |
          <html>
            <body>
              <h1>PHP <?php echo phpversion(); ?></h1>
              <div>
              <?php
                $h = 'localhost';
                $d = 'lamp_db';
                $u = 'lamp_user';
                $p = 'lamp_user_password';

                try {
                  $connection = new PDO("mysql:host=$h;dbname=$d", $u, $p);
                  $connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                }
                catch (PDOException $e) {
                  echo 'ERROR: ' . $e->getMessage();
                }

                $dbs = $connection->query('SHOW DATABASES');

                while (($db = $dbs->fetchColumn(0)) !== FALSE) {
                  echo $db . '<br>';
                }
              ?>
              </div>
            </body>
          </html>
        dest: "/var/www/lamp/web/index.php"
        owner: "jenkins"
        group: "jenkins"
        mode: "u=rw,go=r"
